// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apuqwqvilacpnrtgguap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwdXF3cXZpbGFjcG5ydGdndWFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5OTE3NTksImV4cCI6MjA3NDU2Nzc1OX0.Y_xnjLomUCc7KGu3WhwmEMfIE4wpsGFXoHWfHC56j78";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});